services:
  database:
    container_name: target-solutions-challenge
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB=target-solutions
    expose:
      - 3306

    app:
      depends_on:
        - mysqldb
      build: ./target-solutions-app
      restart: on-failure
      env_file: ./.env
      ports:
        8080:8080
      environment:
        SPRING_APPLICATION_JSON: ./application.properties
